version: '3'
services:

    web:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - 8080:81
        volumes:
            - ./site.conf:/etc/nginx/conf.d/site.conf
        depends_on:
            - node
        networks:
            - app-network

    node:
        build:
            context: ./
            dockerfile: node.dockerfile
        container_name: node
        volumes:
            - ./challenge:/home/fullcycle
        ports:
            - 3000:3000
        depends_on:
            - db
        networks:
            - app-network

    db:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: mysql
        ports:
            - 3306:3306
        restart: always
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: gustavo
            MYSQL_DATABASE: fullcycle
            MYSQL_USER: gustavo
            MYSQL_PASSWORD: gustavo
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

